### ISSUE TITLE
Sentry Cron monitoring support

### ISSUE THREAD

**Issue by lacolaco** [robertcepa/toucan-js#203]
https://docs.sentry.io/platforms/node/crons/

Sentry will support cron monitoring. It is good to use with the cf `scheduled` trigger. I hope toucan-js will integrate with it.

**Comment by timfish** [comment]
I'm guessing parts of this will need to be copied form the node client:
https://github.com/getsentry/sentry-javascript/blob/5fdaaa7234804fecaa25803ced39f601c6175cf4/packages/node/src/client.ts#L166

**Comment by timfish** [comment]
[I'm in the process](https://github.com/getsentry/sentry-javascript/pull/8930) of moving check-in support to a shared client in `@sentry/core`, currently named `ServerRuntimeClient`.

After this is released, the toucan client should be able to extend that rather than the `BaseClient` and this will add support for check-ins/cron monitoring.
