### ISSUE TITLE
dsn vs transportOptions.dsn in options?

### ISSUE THREAD

**Issue by maciejp-ro** [robertcepa/toucan-js#38]
In Toucan options there are now two places for DSN:

 - `dsn` (has star in README, optional in code)
 - `transportOptions.dsn` (described as string in README, a `DsnLike` from `@sentry/types` in code)

Both can only be set at initialization. What is the difference between these options? Looking at the code, it seems like `transportOptions.dsn` is used to rewrite `options.dsn`, the purpose behind this is unclear and not documented.

**Comment by robertcepa** [comment]
I do agree that this is confusing. I was OK with the initial PR from @thibmeu because the `dsn` in `TransportOptions` type from Sentry is required. But now I checked how other JS SDKs handle this and I found that they do not allow `dsn` in `transportOptions` at all.
https://github.com/getsentry/sentry-javascript/blob/master/packages/browser/src/backend.ts#L43
https://github.com/getsentry/sentry-javascript/blob/master/packages/node/src/backend.ts#L53

We should probably join the gang so people used to use these libs don't have to shift the mindset.

**Comment by robertcepa** [comment]
The way these libs handle it is pretty strange though. While they use `options.dsn` to set `options.transportOptions.dsn`, it seems they do not make `dsn` in `TransportOptions` type optional. So TypeScript users who use `transportOptions` need to set `dsn` in both places to pass the type-check.

**Comment by robertcepa** [comment]
Let's have one single source of truth for `dsn` settings. Released in `2.0.0`.
https://github.com/robertcepa/toucan-js/releases/tag/v2.0.0

**Comment by maciejp-ro** [comment]
It's clear now, thank you!
